blog/urls.py
from django.contrib import admin
from django.urls import path,include
from makale import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('about/', views.about, name = "about"),
    path('makale/', include("makale.urls")),
    path('user/', include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

makale/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = "makale"

urlpatterns = [
    path('dashboard/', views.dashboard, name = "dashboard"),
    path('makaleekle/', views.makaleekle, name = "makaleekle"),
    path('makale/<int:id>', views.detail, name = "detail"),
    path('update/<int:id>', views.updateArticle, name = "update"),
    path('delete/<int:id>', views.deleteArticle, name = "delete"),
    path('', views.makale, name = "makale"),
    path('comment/<int:id>', views.addComment, name = "comment"),
]

user/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name = "register"),
    path('login/', views.loginUser, name = "loginUser"),
    path('logout/', views.logoutUser, name = "logoutUser"),
]

makale/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Makale(models.Model):
    yazar = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Yazar")
    baslik = models.CharField(max_length = 50,verbose_name="Başlık")
    icerik = RichTextField()
    olusturmaZamani = models.DateTimeField(auto_now_add = True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank = True, null = True,verbose_name="Foto Ekle",upload_to='media/')
    def __str__(self):
        return self.baslik

    class Meta:
        ordering = ['-olusturmaZamani']

class Comment(models.Model):
    article = models.ForeignKey(Makale, on_delete = models.CASCADE, verbose_name = "makale", related_name = "comments")
    comment_author = models.CharField(max_length = 50, verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200, verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return self.comment_content
    
    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

makale/forms.py
from django import forms
from .models import Makale

class MakaleForm(forms.ModelForm):
    class Meta:
        model = Makale
        fields = ["baslik","icerik","article_image"]

user/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50, label = "Kullanıcı Adı")
    password = forms.CharField(max_length = 20, label = "Parola", widget = forms.PasswordInput)
    confirm = forms.CharField(max_length = 20 , label = "Parola Doğrula",widget = forms.PasswordInput)
    
class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı Adı")
    password = forms.CharField(label = "Parola", widget = forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password!=confirm:
            raise forms.ValidationError("Parolalar Eşleşmiyor")
        
        values = {
            "username" : username,
            "password" : password
        }

        return values

makale/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import MakaleForm
from .models import Makale, Comment
from django.contrib import messages
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
# Create your views here.

def makale(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Makale.objects.filter(baslik__contains = keyword)
        return render(request,"articles.html",{"articles":articles})

    articles = Makale.objects.all()
    return render(request,"articles.html",{"articles":articles})

def index(request):
    context = {
        "bir" : "Hele hele",
        "iki" : "Zamazink",
        "üç" : [1,2,3,4,5]
    }
    return render(request, "index.html", context)

def about(request):
    return render(request, "about.html")

def detail(request,id):
    return HttpResponse("Detail "+str(id))

@login_required(login_url = "user:loginUser")
def dashboard(request):
    makaleler = Makale.objects.filter(yazar = request.user)
    context = {
        "makaleler":makaleler
    }
    return render(request, "dashboard.html",context)

@login_required(login_url = "user:loginUser")
def makaleekle(request):
    form = MakaleForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        makale = form.save(commit = False)
        makale.yazar = request.user
        makale.save()
        messages.success(request,"Makale oluşturuldu")
        return redirect("makale:dashboard")
    return render(request,"makaleekle.html",{"form":form})

def detail(request,id):
    makaleler = get_object_or_404(Makale, id=id)

    comments = makaleler.comments.all()

    return render(request, "detail.html",{"makaleler":makaleler,"comments":comments})

@login_required(login_url = "user:loginUser")
def updateArticle(request,id):
    article = get_object_or_404(Makale, id = id)
    form = MakaleForm(request.POST or None, request.FILES or None, instance = article)

    if form.is_valid():
        article = form.save(commit=False)
        article.yazar = request.user
        article.save()

        messages.success(request,"Makale Guncellendi")
        return redirect("makale:dashboard")

    return render(request, "update.html", {"form":form})

@login_required(login_url = "user:loginUser")
def deleteArticle(request,id):
    article = get_object_or_404(Makale, id = id)
    article.delete()

    messages.success(request,"Sildik")

    return redirect("makale:dashboard")

def addComment(request, id):
    article = get_object_or_404(Makale,id=id)
    
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author, comment_content = comment_content)

        newComment.article = article

        newComment.save()
    
    return redirect(reverse("makale:detail", kwargs={"id":id}))
    

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm, LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
# Create your views here.

def register(request):

    form = RegisterForm(request.POST or None) #Bu b satır aşşaki şiyleri kapsıyo
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username = username)
        newUser.set_password(password)
        newUser.save()
        login(request,newUser),
        messages.info(request,"Kaydoldun geç")

        return redirect("index")

    context = {"form" : form,}
    return render(request,"register.html", context)

    """if request.method == "POST":
        context = {"form" : form,}
        return render(request,"register.html", context)
    else:
        form = RegisterForm()
        context = {"form" : form}
        return render(request,"register.html", context)"""

def loginUser(request):
    form = LoginForm(request.POST or None)

    context = {
        "form" : form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username= username, password = password)

        if user == None:
            messages.info(request,"Kullanıcı adı veya parola hatıalı")
            return render(request, "login.html", context)
        
        messages.success(request, "İçerdesin evlat")

        login(request,user)
        return redirect("index")

    return render(request, "login.html", context)

    return render(request,"login.html")

def logoutUser(request):
    logout(request)
    messages.success(request,"Çehdi Gitti")
    return redirect("index")

templates/about.html
{% extends 'layout.html' %}

{% block body %}
<br/><br/>
<h3>Hakkımda</h3>
    <hr/>
    <p>
        Aliquam vel blandit eros. Etiam placerat diam sapien, sit amet imperdiet lectus suscipit sed. Phasellus sit amet aliquam massa, hendrerit blandit orci. Curabitur pellentesque dolor libero, a elementum diam laoreet sit amet. Nam pharetra orci sit amet nisl consequat, quis ultricies lacus laoreet. Nulla a sapien lobortis, volutpat mi et, tempor turpis. Nullam arcu risus, auctor nec felis quis, auctor laoreet libero. Ut porttitor lobortis gravida.
    </p>
    <p>
        Nulla sollicitudin eros neque. Fusce malesuada luctus nulla, laoreet interdum erat rhoncus ac. Integer ultrices mauris turpis. Sed pulvinar ante eu blandit condimentum. Maecenas eleifend ornare ante, at pretium augue consectetur eget. Suspendisse convallis nulla vel convallis rutrum. Nulla eget dictum ligula. Donec feugiat purus id erat rutrum vulputate. Maecenas ac sodales elit. Nulla vitae congue dolor. Praesent vitae orci elementum, laoreet odio ac, sagittis turpis. Proin viverra consectetur malesuada. Integer eget eleifend tortor.
    </p>
    <hr/>
{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

    <h3>Makaleler</h3><hr>
    <div class="row">
        <form>
            {% csrf_token %}
            <input type="text" name="keyword" class="input-sm" maxlength="64" placeholder="Ne var.." />
            <button type="submit" class="btn btn-primary">Ara</button>
        </from>
    </div>

    {% if articles %}
        {% for makaleler in articles %}
            <div class="row">
                <!-- Post Content Column -->
                <div class="col-lg-8">
                    <!-- Title -->
                    <a href="{% url 'makale:detail' makaleler.id %}" target="blank"> 
                        <h1 class="mt-4">{{makaleler.baslik}}</h1>
                    </a>
                        <!-- Author -->
                    <p class="lead">
                        by
                        <a href="#">{{makaleler.yazar}}</a>
                    </p><hr>
                    <!-- Date/Time -->
                    <p>{{makaleler.oluşturmaZamanı}}</p><hr>
                    <!-- Preview Image -->
                    {% if makaleler.article_image %}
                        <a href="{% url 'makale:detail' makaleler.id %}" target="blank">
                            <img class="img-fluid rounded" src="{{makaleler.article_image.url}}" alt="">
                        </a>
                    {% endif %}<hr>
                    <!-- Post Content -->
                    <p class="lead">
                        {{makaleler.icerik | safe | truncatewords:6 }}
                        <a href="{% url 'makale:detail' makaleler.id %}" class="btn btn-warning">Oku la devamını</a>
                    </p>      
                    <hr>
                </div>
            </div>
        {% endfor %}

    {%else%}
    <p class="alert alert-danger">"Yok bişi</p>
    {% endif %}
    
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

    <h3>Kontrol Paneli</h3><hr>
    <p>Hoşgeldin <small>{{request.user.username}}</small></p><hr>
    <a class="btn btn-success" href="/makale/makaleekle">Makale++</a><hr>

    {% if makaleler %}

    <table class="table">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">Ba?l?k</th>
          <th scope="col">Yazar</th>
          <th scope="col">Guncelle</th>
          <th scope="col">Sil</th>
        </tr>
      </thead>
      <tbody>
        {% for makale in makaleler %}
              <tr>
                  <th scope="row">{{ makale.id }}</th>
                  <td><a href="{% url 'makale:detail' makale.id %}">{{ makale.baslik }}</a></td>
                  <td>{{ makale.yazar.username }}</td>
                  <td><a href="{% url 'makale:update' makale.id %}" class="btn btn-danger">Guncelle</a></td>
                  <td><a href="{% url 'makale:delete' makale.id %}" class="btn btn-danger">Sil</a></td>
              </tr>
        {% endfor %}  
      </tbody>
    </table>

    {% else %}

      <div class="alert alert-danger">Yok makale</div>

    {% endif %}
    
    

{% endblock  %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
<div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{makaleler.baslik}}</h1>

        <!-- Author -->
        <p class="lead">
            by
            <a href="#">{{makaleler.yazar}}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{makaleler.oluşturmaZamanı}}</p>

        <hr>

        <!-- Preview Image -->
        {% if makaleler.article_image %}
            <img class="img-fluid rounded" src="{{makaleler.article_image.url}}" alt="">
        {% endif %}
        <hr>

        <!-- Post Content -->
        <p class="lead">
            {{makaleler.icerik | safe}}
        </p>
            
        <hr>
        {% if comments %}
        {% for comment in comments %}
          
          <div class="row bootstrap snippets">
            <div class="col-md-6 col-md-offset-2 col-sm-12">
                <div class="comment-wrapper">
                    <div class="panel panel-info">
                            <ul class="media-list">
                                <li class="media">
                                    <a href="#" class="pull-left">
                                        <img src="https://bootdey.com/img/Content/user_1.jpg" alt="" class="img-circle">
                                    </a>
                                    <div class="media-body">
                                        <span class="text-muted pull-right">
                                            <small class="text-muted">{{comment.comment_date}}</small>
                                        </span>
                                        <strong class="text-success">{{comment.comment_author}}</strong>
                                        <p>
                                            {{comment.comment_content}}
                                        </p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div> 
            </div>
          </div>

        {% endfor %}
        {% else %}
          <div class="alert alert-danger">Yok yorum</div>
        {% endif %}
        <form method="post" action="{% url 'makale:comment' makaleler.id  %}">
            {% csrf_token %}
            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input name="comment_content" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Yaz">
              <small id="emailHelp" class="form-text text-muted">Bilgileriniz Bizde Saklı Bremınlar ;)</small>
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input name="comment_author" type="text" class="form-control" id="exampleInputPassword1" placeholder="İsim">
            </div>
            <div class="form-group form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>

    </div>

    

</div>



{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">Blog</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'about' %}">Hakkımda</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'makale:makale' %}">Makaleler</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'makale:dashboard' %}">
                Kontrol Paneli
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'user:logoutUser' %}">
                Terkol
              </a>
            </li>
          {% else  %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'user:loginUser' %}">Giriş</a>
            </li>
          {% endif %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:register' %}">Kaydol</a>
          </li>
        </ul>

      </div>
    </nav>

templates/includes/posttemplate.html
<div class="row align-items-center justify-content-between h-100">
    <div class="col">
        <i class="fab fa-github text-github small"></i>
        <a class="small" href="https://github.com/BlackrockDigital/startbootstrap-blog-post">View on GitHub</a>
    </div>
    <div class="col d-none d-lg-block">
        <ul class="nav responsive-toggler justify-content-center" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="desktopToggle" data-toggle="tab" href="#" role="tab"
                    aria-selected="true">
                    <i class="fal fa-desktop"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="mobileToggle" data-toggle="tab" href="#" role="tab" aria-selected="false">
                    <i class="fal fa-mobile"></i>
                </a>
            </li>
        </ul>
    </div>
    <div class="col text-right">
        <a href="https://github.com/BlackrockDigital/startbootstrap-blog-post/archive/gh-pages.zip"
            class="btn btn-primary btn-sm mr-2 d-none d-md-inline-block"
            onclick="if (!window.__cfRLUnblockHandlers) return false; ga('send','event','Download','click','Blog Post')"
            data-cf-modified-9b881331224e3a4b3895899f-="">Free Download</a>
        <a href="https://blackrockdigital.github.io/startbootstrap-blog-post/" class="btn btn-link btn-sm"><i
                class="fal fa-times mr-1"></i> Remove Frame</a>
    </div>
</div>

templates/index.html
{% extends 'layout.html' %}

{% block body %}
    <div class="jumbotron text-center">
        <h3>Hele Hele</h3>
        <p>Riki riki rambo reste rambo bara bara pişko mingo</p> 
    </div>

    <p>
        {% if request.user.is_authenticated %}
            Naber lan {{ request.user.username }}
        {% else  %}
            Yok giriş
        {% endif %}
    </p>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cango</title>
    <link rel="stylesheet" href="{% static '\css\bootstrap.min.css' %}">
</head>
<body>
    
    {% include "includes/navbar.html" %}

     <div style="margin-top: 5%;" class="container" ><br><br>
     {% if messages %}
            {% for message in messages %}

                {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endif %}

            {% endfor %}
    {% endif %}
        {% block body %}
        {% endblock  %}
     </div>
<script src="{% static '\js\bootstrap.min.js' %}"></script>
<script src="{% static '\js\jquery-3.2.1.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html> 

templates/login.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}
<br><br>

<div class="col-md-6 offset-md-3 text-center">
    <h3>Giriş Yap</h3><hr/>
    <form method = "post"> 
            {% csrf_token %}
            {{form|crispy}}
         <br>
        <button type="submit" class="btn btn-success">Gir</button>
    </form>
</div>

{% endblock body %}

templates/makaleekle.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <br><br>

    <div class="col-md-6 offset-md-3 text-center">
        <h3>Ver Makale</h3><hr/>
        <form method = "post" enctype="multipart/form-data"> 
                {% csrf_token %}
                {{form.media}}
                {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-success">Gir</button>
        </form>
    </div>

{% endblock body %}

templates/register.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}
<br><br>

<div class="col-md-6 offset-md-3 text-center">
    <h3>Kaydol</h3><hr/>
    <form method = "post"> 
            {% csrf_token %}
            {{form|crispy}}
         <br>
        <button type="submit" class="btn btn-success">Gir</button>
    </form>
</div>
{% endblock body %}

templates/update.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <br><br>

    <div class="col-md-6 offset-md-3 text-center">
        <h3>Güncelle Şını</h3><hr/>
        <form method = "post" enctype="multipart/form-data"> 
                {% csrf_token %}
                {{form.media}}
                {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-success">Guncalla</button>
        </form>
    </div>

{% endblock body %}